//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoMatching.proto
// Note: requires additional types generated from: model/ProtoPlayer.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_matching_in")]
  public partial class req_matching_in : global::ProtoBuf.IExtensible
  {
    public req_matching_in() {}
    
    private uint _gameType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint gameType
    {
      get { return _gameType; }
      set { _gameType = value; }
    }
    private uint _people;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"people", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint people
    {
      get { return _people; }
      set { _people = value; }
    }
    private uint _distance;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_matching_out")]
  public partial class req_matching_out : global::ProtoBuf.IExtensible
  {
    public req_matching_out() {}
    
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private ulong _matchingId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"matchingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong matchingId
    {
      get { return _matchingId; }
      set { _matchingId = value; }
    }
    private uint _hiRange;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hiRange", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hiRange
    {
      get { return _hiRange; }
      set { _hiRange = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_cancel_matching_in")]
  public partial class req_cancel_matching_in : global::ProtoBuf.IExtensible
  {
    public req_cancel_matching_in() {}
    
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private ulong _matchingId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"matchingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong matchingId
    {
      get { return _matchingId; }
      set { _matchingId = value; }
    }
    private uint _hiRange;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hiRange", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hiRange
    {
      get { return _hiRange; }
      set { _hiRange = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_cancel_matching_handle")]
  public partial class req_cancel_matching_handle : global::ProtoBuf.IExtensible
  {
    public req_cancel_matching_handle() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_matching_result_out")]
  public partial class notify_matching_result_out : global::ProtoBuf.IExtensible
  {
    public notify_matching_result_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.player_simple_info> _players = new global::System.Collections.Generic.List<com.sporger.server.proto.model.player_simple_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.player_simple_info> players
    {
      get { return _players; }
    }
  
    private uint _randomSceneId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"randomSceneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint randomSceneId
    {
      get { return _randomSceneId; }
      set { _randomSceneId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_enter_pre_scene_in")]
  public partial class req_enter_pre_scene_in : global::ProtoBuf.IExtensible
  {
    public req_enter_pre_scene_in() {}
    
    private ulong _matchingId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"matchingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong matchingId
    {
      get { return _matchingId; }
      set { _matchingId = value; }
    }
    private uint _hiRange;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hiRange", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hiRange
    {
      get { return _hiRange; }
      set { _hiRange = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_player_ready_enter_pre_scene_out")]
  public partial class notify_player_ready_enter_pre_scene_out : global::ProtoBuf.IExtensible
  {
    public notify_player_ready_enter_pre_scene_out() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_permite_enter_pre_scene_out")]
  public partial class notify_permite_enter_pre_scene_out : global::ProtoBuf.IExtensible
  {
    public notify_permite_enter_pre_scene_out() {}
    
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private string _channelId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_select_scene_in")]
  public partial class req_select_scene_in : global::ProtoBuf.IExtensible
  {
    public req_select_scene_in() {}
    
    private uint _sceneId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sceneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sceneId
    {
      get { return _sceneId; }
      set { _sceneId = value; }
    }
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_change_scene_out")]
  public partial class notify_change_scene_out : global::ProtoBuf.IExtensible
  {
    public notify_change_scene_out() {}
    
    private uint _sceneId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sceneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sceneId
    {
      get { return _sceneId; }
      set { _sceneId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_ready_in")]
  public partial class req_ready_in : global::ProtoBuf.IExtensible
  {
    public req_ready_in() {}
    
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_ready_out")]
  public partial class notify_ready_out : global::ProtoBuf.IExtensible
  {
    public notify_ready_out() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_change_room_owner_out")]
  public partial class notify_change_room_owner_out : global::ProtoBuf.IExtensible
  {
    public notify_change_room_owner_out() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_start_race_in")]
  public partial class req_start_race_in : global::ProtoBuf.IExtensible
  {
    public req_start_race_in() {}
    
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_start_race_out")]
  public partial class req_start_race_out : global::ProtoBuf.IExtensible
  {
    public req_start_race_out() {}
    
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}