//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoSquare.proto
// Note: requires additional types generated from: model/ProtoFriend.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_advertisement")]
  public partial class notify_advertisement : global::ProtoBuf.IExtensible
  {
    public notify_advertisement() {}
    
    private readonly global::System.Collections.Generic.List<string> _content = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> content
    {
      get { return _content; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_enter_square_map_in")]
  public partial class req_enter_square_map_in : global::ProtoBuf.IExtensible
  {
    public req_enter_square_map_in() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_enter_square_map_out")]
  public partial class req_enter_square_map_out : global::ProtoBuf.IExtensible
  {
    public req_enter_square_map_out() {}
    
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.square_chat_group> _groupList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.square_chat_group>();
    [global::ProtoBuf.ProtoMember(3, Name=@"groupList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.square_chat_group> groupList
    {
      get { return _groupList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"square_chat_group")]
  public partial class square_chat_group : global::ProtoBuf.IExtensible
  {
    public square_chat_group() {}
    
    private ulong _groupID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong groupID
    {
      get { return _groupID; }
      set { _groupID = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _groupTitle;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"groupTitle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string groupTitle
    {
      get { return _groupTitle; }
      set { _groupTitle = value; }
    }
    private uint _chatNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"chatNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint chatNum
    {
      get { return _chatNum; }
      set { _chatNum = value; }
    }
    private uint _newChatNum = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"newChatNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint newChatNum
    {
      get { return _newChatNum; }
      set { _newChatNum = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_hot_square_chat_group_in")]
  public partial class req_hot_square_chat_group_in : global::ProtoBuf.IExtensible
  {
    public req_hot_square_chat_group_in() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_hot_square_chat_group_out")]
  public partial class req_hot_square_chat_group_out : global::ProtoBuf.IExtensible
  {
    public req_hot_square_chat_group_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.square_chat_group> _hotGroupList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.square_chat_group>();
    [global::ProtoBuf.ProtoMember(1, Name=@"hotGroupList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.square_chat_group> hotGroupList
    {
      get { return _hotGroupList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_create_square_chat_group_in")]
  public partial class req_create_square_chat_group_in : global::ProtoBuf.IExtensible
  {
    public req_create_square_chat_group_in() {}
    
    private com.sporger.server.proto.model.square_chat_group _groupInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.square_chat_group groupInfo
    {
      get { return _groupInfo; }
      set { _groupInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_create_square_chat_group_out")]
  public partial class req_create_square_chat_group_out : global::ProtoBuf.IExtensible
  {
    public req_create_square_chat_group_out() {}
    
    private com.sporger.server.proto.model.square_chat_group _groupInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.square_chat_group groupInfo
    {
      get { return _groupInfo; }
      set { _groupInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"square_chat_Info")]
  public partial class square_chat_Info : global::ProtoBuf.IExtensible
  {
    public square_chat_Info() {}
    
    private ulong _chatID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong chatID
    {
      get { return _chatID; }
      set { _chatID = value; }
    }
    private com.sporger.server.proto.model.player_base_info _playerInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.player_base_info playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    private uint _sendTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sendTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sendTime
    {
      get { return _sendTime; }
      set { _sendTime = value; }
    }
    private string _content;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_square_chat_Info_in")]
  public partial class req_square_chat_Info_in : global::ProtoBuf.IExtensible
  {
    public req_square_chat_Info_in() {}
    
    private string _content;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private ulong _groupID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"groupID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong groupID
    {
      get { return _groupID; }
      set { _groupID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_square_chat_Info")]
  public partial class notify_square_chat_Info : global::ProtoBuf.IExtensible
  {
    public notify_square_chat_Info() {}
    
    private com.sporger.server.proto.model.square_chat_Info _chatInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chatInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.square_chat_Info chatInfo
    {
      get { return _chatInfo; }
      set { _chatInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_enter_square_chat_group_in")]
  public partial class req_enter_square_chat_group_in : global::ProtoBuf.IExtensible
  {
    public req_enter_square_chat_group_in() {}
    
    private ulong _groupID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong groupID
    {
      get { return _groupID; }
      set { _groupID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_enter_square_chat_group_out")]
  public partial class req_enter_square_chat_group_out : global::ProtoBuf.IExtensible
  {
    public req_enter_square_chat_group_out() {}
    
    private com.sporger.server.proto.model.square_chat_group _groupInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.square_chat_group groupInfo
    {
      get { return _groupInfo; }
      set { _groupInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.square_chat_Info> _chatInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.square_chat_Info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"chatInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.square_chat_Info> chatInfo
    {
      get { return _chatInfo; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.player_base_info> _playerInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.player_base_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.player_base_info> playerInfo
    {
      get { return _playerInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_enter_player_square_chat")]
  public partial class notify_enter_player_square_chat : global::ProtoBuf.IExtensible
  {
    public notify_enter_player_square_chat() {}
    
    private ulong _groupID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong groupID
    {
      get { return _groupID; }
      set { _groupID = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.player_base_info> _playerInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.player_base_info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.player_base_info> playerInfo
    {
      get { return _playerInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_close_square_chat_group_in")]
  public partial class req_close_square_chat_group_in : global::ProtoBuf.IExtensible
  {
    public req_close_square_chat_group_in() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_exit_square_chat_group_in")]
  public partial class req_exit_square_chat_group_in : global::ProtoBuf.IExtensible
  {
    public req_exit_square_chat_group_in() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_close_square_chat_group")]
  public partial class notify_close_square_chat_group : global::ProtoBuf.IExtensible
  {
    public notify_close_square_chat_group() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_exit_square_chat_group")]
  public partial class notify_exit_square_chat_group : global::ProtoBuf.IExtensible
  {
    public notify_exit_square_chat_group() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_square_invite_friend_in")]
  public partial class req_square_invite_friend_in : global::ProtoBuf.IExtensible
  {
    public req_square_invite_friend_in() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private ulong _groupID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"groupID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong groupID
    {
      get { return _groupID; }
      set { _groupID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_square_invite_agree_friend_in")]
  public partial class req_square_invite_agree_friend_in : global::ProtoBuf.IExtensible
  {
    public req_square_invite_agree_friend_in() {}
    
    private uint _inviteId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"inviteId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint inviteId
    {
      get { return _inviteId; }
      set { _inviteId = value; }
    }
    private uint _agree;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"agree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint agree
    {
      get { return _agree; }
      set { _agree = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}