//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoPlayer.proto
// Note: requires additional types generated from: model/ProtoBag.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"player_simple_info")]
  public partial class player_simple_info : global::ProtoBuf.IExtensible
  {
    public player_simple_info() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _playerName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _city;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"city", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint city
    {
      get { return _city; }
      set { _city = value; }
    }
    private uint _sex;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _equipIds = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"equipIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> equipIds
    {
      get { return _equipIds; }
    }
  
    private uint _skeletonType;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"skeletonType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skeletonType
    {
      get { return _skeletonType; }
      set { _skeletonType = value; }
    }
    private bool _isFollow;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"isFollow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isFollow
    {
      get { return _isFollow; }
      set { _isFollow = value; }
    }
    private string _headIcon;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"headIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string headIcon
    {
      get { return _headIcon; }
      set { _headIcon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"player_goin_instance_out")]
  public partial class player_goin_instance_out : global::ProtoBuf.IExtensible
  {
    public player_goin_instance_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.player_simple_info> _player_info = new global::System.Collections.Generic.List<com.sporger.server.proto.model.player_simple_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"player_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.player_simple_info> player_info
    {
      get { return _player_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"player_exit_instance_out")]
  public partial class player_exit_instance_out : global::ProtoBuf.IExtensible
  {
    public player_exit_instance_out() {}
    
    private readonly global::System.Collections.Generic.List<string> _playerId = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> playerId
    {
      get { return _playerId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"player_instance_syncinfo")]
  public partial class player_instance_syncinfo : global::ProtoBuf.IExtensible
  {
    public player_instance_syncinfo() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _distance;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private uint _timestamp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sync_player_instance_pos_out")]
  public partial class sync_player_instance_pos_out : global::ProtoBuf.IExtensible
  {
    public sync_player_instance_pos_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.player_instance_syncinfo> _playersPosInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.player_instance_syncinfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playersPosInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.player_instance_syncinfo> playersPosInfo
    {
      get { return _playersPosInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_player_list_in")]
  public partial class req_player_list_in : global::ProtoBuf.IExtensible
  {
    public req_player_list_in() {}
    
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_player_list_out")]
  public partial class req_player_list_out : global::ProtoBuf.IExtensible
  {
    public req_player_list_out() {}
    
    private readonly global::System.Collections.Generic.List<string> _playerId = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> playerId
    {
      get { return _playerId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_new_player_list_simple_info_in")]
  public partial class req_new_player_list_simple_info_in : global::ProtoBuf.IExtensible
  {
    public req_new_player_list_simple_info_in() {}
    
    private readonly global::System.Collections.Generic.List<string> _playerId = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> playerId
    {
      get { return _playerId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_new_player_list_simple_info_out")]
  public partial class req_new_player_list_simple_info_out : global::ProtoBuf.IExtensible
  {
    public req_new_player_list_simple_info_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.player_simple_info> _player_info = new global::System.Collections.Generic.List<com.sporger.server.proto.model.player_simple_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"player_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.player_simple_info> player_info
    {
      get { return _player_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}