//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoSearchTreasure.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_open_treasure_box_in")]
  public partial class req_open_treasure_box_in : global::ProtoBuf.IExtensible
  {
    public req_open_treasure_box_in() {}
    
    private uint _spawn_point_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"spawn_point_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint spawn_point_id
    {
      get { return _spawn_point_id; }
      set { _spawn_point_id = value; }
    }
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_open_treasure_box_out")]
  public partial class req_open_treasure_box_out : global::ProtoBuf.IExtensible
  {
    public req_open_treasure_box_out() {}
    
    private uint _spawn_point_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"spawn_point_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint spawn_point_id
    {
      get { return _spawn_point_id; }
      set { _spawn_point_id = value; }
    }
    private bool _isSuccess;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isSuccess", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isSuccess
    {
      get { return _isSuccess; }
      set { _isSuccess = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"scene_item_info")]
  public partial class scene_item_info : global::ProtoBuf.IExtensible
  {
    public scene_item_info() {}
    
    private uint _spawn_point;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"spawn_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint spawn_point
    {
      get { return _spawn_point; }
      set { _spawn_point = value; }
    }
    private uint _item_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"item_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint item_type
    {
      get { return _item_type; }
      set { _item_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"scene_box_info")]
  public partial class scene_box_info : global::ProtoBuf.IExtensible
  {
    public scene_box_info() {}
    
    private uint _spawn_point;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"spawn_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint spawn_point
    {
      get { return _spawn_point; }
      set { _spawn_point = value; }
    }
    private uint _box_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"box_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint box_type
    {
      get { return _box_type; }
      set { _box_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"mp_ordinary_box_info")]
  public partial class mp_ordinary_box_info : global::ProtoBuf.IExtensible
  {
    public mp_ordinary_box_info() {}
    
    private uint _spawn_point;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"spawn_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint spawn_point
    {
      get { return _spawn_point; }
      set { _spawn_point = value; }
    }
    private uint _standPosCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"standPosCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint standPosCount
    {
      get { return _standPosCount; }
      set { _standPosCount = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.StandPointState> _standPointStateList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.StandPointState>();
    [global::ProtoBuf.ProtoMember(3, Name=@"standPointStateList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.StandPointState> standPointStateList
    {
      get { return _standPointStateList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_box_and_item_list_out")]
  public partial class notify_box_and_item_list_out : global::ProtoBuf.IExtensible
  {
    public notify_box_and_item_list_out() {}
    
    private readonly global::System.Collections.Generic.List<uint> _ordinary_box_spawn_point_list = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ordinary_box_spawn_point_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> ordinary_box_spawn_point_list
    {
      get { return _ordinary_box_spawn_point_list; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.scene_box_info> _item_box_spawn_point_list = new global::System.Collections.Generic.List<com.sporger.server.proto.model.scene_box_info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"item_box_spawn_point_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.scene_box_info> item_box_spawn_point_list
    {
      get { return _item_box_spawn_point_list; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.scene_item_info> _item_spawn_point_list = new global::System.Collections.Generic.List<com.sporger.server.proto.model.scene_item_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"item_spawn_point_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.scene_item_info> item_spawn_point_list
    {
      get { return _item_spawn_point_list; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.mp_ordinary_box_info> _mp_ordinary_box_info_list = new global::System.Collections.Generic.List<com.sporger.server.proto.model.mp_ordinary_box_info>();
    [global::ProtoBuf.ProtoMember(4, Name=@"mp_ordinary_box_info_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.mp_ordinary_box_info> mp_ordinary_box_info_list
    {
      get { return _mp_ordinary_box_info_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_spawn_ordinary_box_out")]
  public partial class notify_spawn_ordinary_box_out : global::ProtoBuf.IExtensible
  {
    public notify_spawn_ordinary_box_out() {}
    
    private readonly global::System.Collections.Generic.List<uint> _ordinary_box_spawn_point_list = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ordinary_box_spawn_point_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> ordinary_box_spawn_point_list
    {
      get { return _ordinary_box_spawn_point_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_spawn_item_and_box_out")]
  public partial class notify_spawn_item_and_box_out : global::ProtoBuf.IExtensible
  {
    public notify_spawn_item_and_box_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.scene_box_info> _item_box_spawn_point_list = new global::System.Collections.Generic.List<com.sporger.server.proto.model.scene_box_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item_box_spawn_point_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.scene_box_info> item_box_spawn_point_list
    {
      get { return _item_box_spawn_point_list; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.scene_item_info> _item_spawn_point_list = new global::System.Collections.Generic.List<com.sporger.server.proto.model.scene_item_info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"item_spawn_point_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.scene_item_info> item_spawn_point_list
    {
      get { return _item_spawn_point_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_spawn_mp_ordinary_box_out")]
  public partial class notify_spawn_mp_ordinary_box_out : global::ProtoBuf.IExtensible
  {
    public notify_spawn_mp_ordinary_box_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.mp_ordinary_box_info> _mp_ordinary_box_info_list = new global::System.Collections.Generic.List<com.sporger.server.proto.model.mp_ordinary_box_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mp_ordinary_box_info_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.mp_ordinary_box_info> mp_ordinary_box_info_list
    {
      get { return _mp_ordinary_box_info_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_open_treasure_box_out")]
  public partial class notify_open_treasure_box_out : global::ProtoBuf.IExtensible
  {
    public notify_open_treasure_box_out() {}
    
    private uint _spawn_point_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"spawn_point_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint spawn_point_id
    {
      get { return _spawn_point_id; }
      set { _spawn_point_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_pick_open_treasure_box_item_in")]
  public partial class req_pick_open_treasure_box_item_in : global::ProtoBuf.IExtensible
  {
    public req_pick_open_treasure_box_item_in() {}
    
    private uint _spawn_point_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"spawn_point_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint spawn_point_id
    {
      get { return _spawn_point_id; }
      set { _spawn_point_id = value; }
    }
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_pick_open_treasure_box_item_out")]
  public partial class req_pick_open_treasure_box_item_out : global::ProtoBuf.IExtensible
  {
    public req_pick_open_treasure_box_item_out() {}
    
    private com.sporger.server.proto.model.fam_item_bar_item_info _item_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"item_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.fam_item_bar_item_info item_info
    {
      get { return _item_info; }
      set { _item_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_pick_open_treasure_item_out")]
  public partial class notify_pick_open_treasure_item_out : global::ProtoBuf.IExtensible
  {
    public notify_pick_open_treasure_item_out() {}
    
    private uint _spawn_point_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"spawn_point_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint spawn_point_id
    {
      get { return _spawn_point_id; }
      set { _spawn_point_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_enter_fam_in")]
  public partial class req_enter_fam_in : global::ProtoBuf.IExtensible
  {
    public req_enter_fam_in() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_enter_fam_out")]
  public partial class req_enter_fam_out : global::ProtoBuf.IExtensible
  {
    public req_enter_fam_out() {}
    
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private uint _state;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private string _timescale;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"timescale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string timescale
    {
      get { return _timescale; }
      set { _timescale = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_enter_fam_map_in")]
  public partial class req_enter_fam_map_in : global::ProtoBuf.IExtensible
  {
    public req_enter_fam_map_in() {}
    
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_enter_fam_map_out")]
  public partial class req_enter_fam_map_out : global::ProtoBuf.IExtensible
  {
    public req_enter_fam_map_out() {}
    
    private uint _cutType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cutType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cutType
    {
      get { return _cutType; }
      set { _cutType = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.fam_map_info> _mapInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.fam_map_info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"mapInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.fam_map_info> mapInfo
    {
      get { return _mapInfo; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.fam_item_bar_item_info> _famItemBarItemInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.fam_item_bar_item_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"famItemBarItemInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.fam_item_bar_item_info> famItemBarItemInfo
    {
      get { return _famItemBarItemInfo; }
    }
  
    private string _channelId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"fam_map_info")]
  public partial class fam_map_info : global::ProtoBuf.IExtensible
  {
    public fam_map_info() {}
    
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _mapIndex = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"mapIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> mapIndex
    {
      get { return _mapIndex; }
    }
  
    private uint _direction;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"fam_item_bar_item_info")]
  public partial class fam_item_bar_item_info : global::ProtoBuf.IExtensible
  {
    public fam_item_bar_item_info() {}
    
    private uint _itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private uint _treasureBoxSpawnPoint;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"treasureBoxSpawnPoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint treasureBoxSpawnPoint
    {
      get { return _treasureBoxSpawnPoint; }
      set { _treasureBoxSpawnPoint = value; }
    }
    private uint _slot;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"slot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint slot
    {
      get { return _slot; }
      set { _slot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_discard_open_treasure_box_item_in")]
  public partial class req_discard_open_treasure_box_item_in : global::ProtoBuf.IExtensible
  {
    public req_discard_open_treasure_box_item_in() {}
    
    private uint _slot;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"slot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint slot
    {
      get { return _slot; }
      set { _slot = value; }
    }
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_discard_open_treasure_box_item_out")]
  public partial class req_discard_open_treasure_box_item_out : global::ProtoBuf.IExtensible
  {
    public req_discard_open_treasure_box_item_out() {}
    
    private uint _slot;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"slot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint slot
    {
      get { return _slot; }
      set { _slot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_open_mp_ordinary_box_stand_pos_out")]
  public partial class notify_open_mp_ordinary_box_stand_pos_out : global::ProtoBuf.IExtensible
  {
    public notify_open_mp_ordinary_box_stand_pos_out() {}
    
    private uint _standPos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"standPos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint standPos
    {
      get { return _standPos; }
      set { _standPos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_restore_mp_ordinary_box_stand_pos_out")]
  public partial class notify_restore_mp_ordinary_box_stand_pos_out : global::ProtoBuf.IExtensible
  {
    public notify_restore_mp_ordinary_box_stand_pos_out() {}
    
    private uint _standPos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"standPos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint standPos
    {
      get { return _standPos; }
      set { _standPos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"StandPointState")]
    public enum StandPointState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVE", Value=1)]
      ACTIVE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEACTIVE", Value=2)]
      DEACTIVE = 2
    }
  
}