//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoCharacterAttribute.proto
// Note: requires additional types generated from: model/ProtoBag.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"character_attribute_in")]
  public partial class character_attribute_in : global::ProtoBuf.IExtensible
  {
    public character_attribute_in() {}
    
    private string _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"character_attribute_out")]
  public partial class character_attribute_out : global::ProtoBuf.IExtensible
  {
    public character_attribute_out() {}
    
    private com.sporger.server.proto.model.sporger_info _sporger = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sporger", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.sporger_info sporger
    {
      get { return _sporger; }
      set { _sporger = value; }
    }
    private int _lv = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private float _strength = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"strength", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float strength
    {
      get { return _strength; }
      set { _strength = value; }
    }
    private int _pace = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pace", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pace
    {
      get { return _pace; }
      set { _pace = value; }
    }
    private int _gold = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _exp = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _diamond = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private int _honour = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"honour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int honour
    {
      get { return _honour; }
      set { _honour = value; }
    }
    private int _careerMapId = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"careerMapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int careerMapId
    {
      get { return _careerMapId; }
      set { _careerMapId = value; }
    }
    private string _userName = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.game_item_info> _bag = new global::System.Collections.Generic.List<com.sporger.server.proto.model.game_item_info>();
    [global::ProtoBuf.ProtoMember(11, Name=@"bag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.game_item_info> bag
    {
      get { return _bag; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.game_item_detail_info> _equips = new global::System.Collections.Generic.List<com.sporger.server.proto.model.game_item_detail_info>();
    [global::ProtoBuf.ProtoMember(12, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.game_item_detail_info> equips
    {
      get { return _equips; }
    }
  
    private uint _skeletonType;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"skeletonType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skeletonType
    {
      get { return _skeletonType; }
      set { _skeletonType = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.level_star_info> _levelStarInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.level_star_info>();
    [global::ProtoBuf.ProtoMember(14, Name=@"levelStarInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.level_star_info> levelStarInfo
    {
      get { return _levelStarInfo; }
    }
  
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _cityId = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"cityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cityId
    {
      get { return _cityId; }
      set { _cityId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sporger_index")]
  public partial class sporger_index : global::ProtoBuf.IExtensible
  {
    public sporger_index() {}
    
    private int _speed = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private int _endurance = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"endurance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int endurance
    {
      get { return _endurance; }
      set { _endurance = value; }
    }
    private int _heartLung = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"heartLung", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int heartLung
    {
      get { return _heartLung; }
      set { _heartLung = value; }
    }
    private int _flexibility = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"flexibility", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int flexibility
    {
      get { return _flexibility; }
      set { _flexibility = value; }
    }
    private int _strength = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int strength
    {
      get { return _strength; }
      set { _strength = value; }
    }
    private int _total = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"total", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int total
    {
      get { return _total; }
      set { _total = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sporger_info")]
  public partial class sporger_info : global::ProtoBuf.IExtensible
  {
    public sporger_info() {}
    
    private com.sporger.server.proto.model.sporger_index _sporgerIndex = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sporgerIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.sporger_index sporgerIndex
    {
      get { return _sporgerIndex; }
      set { _sporgerIndex = value; }
    }
    private com.sporger.server.proto.model.sporger_index _sporgerDifferent = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sporgerDifferent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.sporger_index sporgerDifferent
    {
      get { return _sporgerDifferent; }
      set { _sporgerDifferent = value; }
    }
    private com.sporger.server.proto.model.sporger_index _SporgerMax = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"SporgerMax", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.sporger_index SporgerMax
    {
      get { return _SporgerMax; }
      set { _SporgerMax = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"item_change_info")]
  public partial class item_change_info : global::ProtoBuf.IExtensible
  {
    public item_change_info() {}
    
    private uint _itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private int _itemCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"itemCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemCount
    {
      get { return _itemCount; }
      set { _itemCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_character_currency")]
  public partial class notify_character_currency : global::ProtoBuf.IExtensible
  {
    public notify_character_currency() {}
    
    private int _gold = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _diamond = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private int _exp = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.item_change_info> _itemList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.item_change_info>();
    [global::ProtoBuf.ProtoMember(4, Name=@"itemList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.item_change_info> itemList
    {
      get { return _itemList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"character_equip_dress_in")]
  public partial class character_equip_dress_in : global::ProtoBuf.IExtensible
  {
    public character_equip_dress_in() {}
    
    private uint _itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private uint _uniqueId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_character_level_up")]
  public partial class notify_character_level_up : global::ProtoBuf.IExtensible
  {
    public notify_character_level_up() {}
    
    private int _level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _exp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"level_star_info")]
  public partial class level_star_info : global::ProtoBuf.IExtensible
  {
    public level_star_info() {}
    
    private int _levelId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"levelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int levelId
    {
      get { return _levelId; }
      set { _levelId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _levelStarList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"levelStarList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> levelStarList
    {
      get { return _levelStarList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}