//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoMaze.proto
// Note: requires additional types generated from: model/ProtoBag.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_maze_matching_in")]
  public partial class req_maze_matching_in : global::ProtoBuf.IExtensible
  {
    public req_maze_matching_in() {}
    
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_maze_matching_out")]
  public partial class req_maze_matching_out : global::ProtoBuf.IExtensible
  {
    public req_maze_matching_out() {}
    
    private ulong _matchingID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"matchingID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong matchingID
    {
      get { return _matchingID; }
      set { _matchingID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_maze_matching_result_out")]
  public partial class notify_maze_matching_result_out : global::ProtoBuf.IExtensible
  {
    public notify_maze_matching_result_out() {}
    
    private bool _isSuc;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"isSuc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isSuc
    {
      get { return _isSuc; }
      set { _isSuc = value; }
    }
    private ulong _roomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private uint _finishPointId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"finishPointId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint finishPointId
    {
      get { return _finishPointId; }
      set { _finishPointId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_maze_cancel_matching_in")]
  public partial class req_maze_cancel_matching_in : global::ProtoBuf.IExtensible
  {
    public req_maze_cancel_matching_in() {}
    
    private ulong _matchingID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"matchingID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong matchingID
    {
      get { return _matchingID; }
      set { _matchingID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_maze_wait_count_down_out")]
  public partial class notify_maze_wait_count_down_out : global::ProtoBuf.IExtensible
  {
    public notify_maze_wait_count_down_out() {}
    
    private uint _timeLeft;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timeLeft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint timeLeft
    {
      get { return _timeLeft; }
      set { _timeLeft = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_maze_destroy_door_in")]
  public partial class req_maze_destroy_door_in : global::ProtoBuf.IExtensible
  {
    public req_maze_destroy_door_in() {}
    
    private uint _spawnId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"spawnId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint spawnId
    {
      get { return _spawnId; }
      set { _spawnId = value; }
    }
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_maze_destroy_door_out")]
  public partial class req_maze_destroy_door_out : global::ProtoBuf.IExtensible
  {
    public req_maze_destroy_door_out() {}
    
    private uint _spawnId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"spawnId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint spawnId
    {
      get { return _spawnId; }
      set { _spawnId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_maze_destroy_door_out")]
  public partial class notify_maze_destroy_door_out : global::ProtoBuf.IExtensible
  {
    public notify_maze_destroy_door_out() {}
    
    private uint _spawnId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"spawnId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint spawnId
    {
      get { return _spawnId; }
      set { _spawnId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_maze_spawn_door_out")]
  public partial class notify_maze_spawn_door_out : global::ProtoBuf.IExtensible
  {
    public notify_maze_spawn_door_out() {}
    
    private uint _spawnId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"spawnId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint spawnId
    {
      get { return _spawnId; }
      set { _spawnId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_enter_finish_point_in")]
  public partial class req_enter_finish_point_in : global::ProtoBuf.IExtensible
  {
    public req_enter_finish_point_in() {}
    
    private ulong _roomID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_finish_maze_game_out")]
  public partial class notify_finish_maze_game_out : global::ProtoBuf.IExtensible
  {
    public notify_finish_maze_game_out() {}
    
    private bool _isSuccess;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"isSuccess", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isSuccess
    {
      get { return _isSuccess; }
      set { _isSuccess = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.item_simple_info> _itemList = new global::System.Collections.Generic.List<com.sporger.server.proto.model.item_simple_info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"itemList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.item_simple_info> itemList
    {
      get { return _itemList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_maze_character_energe_out")]
  public partial class notify_maze_character_energe_out : global::ProtoBuf.IExtensible
  {
    public notify_maze_character_energe_out() {}
    
    private int _energeValue;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"energeValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int energeValue
    {
      get { return _energeValue; }
      set { _energeValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_maze_pick_energe_item_in")]
  public partial class req_maze_pick_energe_item_in : global::ProtoBuf.IExtensible
  {
    public req_maze_pick_energe_item_in() {}
    
    private int _spawnId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"spawnId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int spawnId
    {
      get { return _spawnId; }
      set { _spawnId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_maze_pick_energe_item_out")]
  public partial class req_maze_pick_energe_item_out : global::ProtoBuf.IExtensible
  {
    public req_maze_pick_energe_item_out() {}
    
    private int _spawnId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"spawnId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int spawnId
    {
      get { return _spawnId; }
      set { _spawnId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_maze_spawn_energe_item_out")]
  public partial class notify_maze_spawn_energe_item_out : global::ProtoBuf.IExtensible
  {
    public notify_maze_spawn_energe_item_out() {}
    
    private readonly global::System.Collections.Generic.List<int> _spawnId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"spawnId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> spawnId
    {
      get { return _spawnId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_maze_pick_energe_item_out")]
  public partial class notify_maze_pick_energe_item_out : global::ProtoBuf.IExtensible
  {
    public notify_maze_pick_energe_item_out() {}
    
    private int _spawnId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"spawnId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int spawnId
    {
      get { return _spawnId; }
      set { _spawnId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}