//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoRunReport.proto
// Note: requires additional types generated from: model/ProtoCharacterAttribute.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"lat_and_long")]
  public partial class lat_and_long : global::ProtoBuf.IExtensible
  {
    public lat_and_long() {}
    
    private float _Latitude;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Latitude", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Latitude
    {
      get { return _Latitude; }
      set { _Latitude = value; }
    }
    private float _longitude;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"longitude", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float longitude
    {
      get { return _longitude; }
      set { _longitude = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"run_report_in")]
  public partial class run_report_in : global::ProtoBuf.IExtensible
  {
    public run_report_in() {}
    
    private float _TotalDistance;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"TotalDistance", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float TotalDistance
    {
      get { return _TotalDistance; }
      set { _TotalDistance = value; }
    }
    private uint _StartTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"StartTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint StartTime
    {
      get { return _StartTime; }
      set { _StartTime = value; }
    }
    private uint _UseTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"UseTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint UseTime
    {
      get { return _UseTime; }
      set { _UseTime = value; }
    }
    private uint _Kcal;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Kcal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Kcal
    {
      get { return _Kcal; }
      set { _Kcal = value; }
    }
    private float _AverageSpeed;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"AverageSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float AverageSpeed
    {
      get { return _AverageSpeed; }
      set { _AverageSpeed = value; }
    }
    private float _MaxSpeed;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"MaxSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float MaxSpeed
    {
      get { return _MaxSpeed; }
      set { _MaxSpeed = value; }
    }
    private readonly global::System.Collections.Generic.List<float> _SpeedPerKm = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(7, Name=@"SpeedPerKm", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> SpeedPerKm
    {
      get { return _SpeedPerKm; }
    }
  
    private uint _StepCount;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"StepCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint StepCount
    {
      get { return _StepCount; }
      set { _StepCount = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _StepPerMin = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(9, Name=@"StepPerMin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> StepPerMin
    {
      get { return _StepPerMin; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.lat_and_long> _LatandLong = new global::System.Collections.Generic.List<com.sporger.server.proto.model.lat_and_long>();
    [global::ProtoBuf.ProtoMember(10, Name=@"LatandLong", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.lat_and_long> LatandLong
    {
      get { return _LatandLong; }
    }
  
    private uint _AltitudeChange;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"AltitudeChange", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AltitudeChange
    {
      get { return _AltitudeChange; }
      set { _AltitudeChange = value; }
    }
    private uint _AverageStep;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"AverageStep", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AverageStep
    {
      get { return _AverageStep; }
      set { _AverageStep = value; }
    }
    private uint _MaxStep;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"MaxStep", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MaxStep
    {
      get { return _MaxStep; }
      set { _MaxStep = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_sporger_change_out")]
  public partial class notify_sporger_change_out : global::ProtoBuf.IExtensible
  {
    public notify_sporger_change_out() {}
    
    private com.sporger.server.proto.model.sporger_info _sporger = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sporger", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.sporger.server.proto.model.sporger_info sporger
    {
      get { return _sporger; }
      set { _sporger = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_run_base_info_in")]
  public partial class req_run_base_info_in : global::ProtoBuf.IExtensible
  {
    public req_run_base_info_in() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_run_base_info_out")]
  public partial class req_run_base_info_out : global::ProtoBuf.IExtensible
  {
    public req_run_base_info_out() {}
    
    private float _totalDistance;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"totalDistance", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float totalDistance
    {
      get { return _totalDistance; }
      set { _totalDistance = value; }
    }
    private uint _itemPVPRanking;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"itemPVPRanking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint itemPVPRanking
    {
      get { return _itemPVPRanking; }
      set { _itemPVPRanking = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_pull_run_record_in")]
  public partial class req_pull_run_record_in : global::ProtoBuf.IExtensible
  {
    public req_pull_run_record_in() {}
    
    private uint _page;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint page
    {
      get { return _page; }
      set { _page = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"run_record")]
  public partial class run_record : global::ProtoBuf.IExtensible
  {
    public run_record() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private float _totalDistance;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"totalDistance", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float totalDistance
    {
      get { return _totalDistance; }
      set { _totalDistance = value; }
    }
    private float _speed;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private float _useTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"useTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float useTime
    {
      get { return _useTime; }
      set { _useTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_pull_run_record_out")]
  public partial class req_pull_run_record_out : global::ProtoBuf.IExtensible
  {
    public req_pull_run_record_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.run_record> _run_record_list = new global::System.Collections.Generic.List<com.sporger.server.proto.model.run_record>();
    [global::ProtoBuf.ProtoMember(1, Name=@"run_record_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.run_record> run_record_list
    {
      get { return _run_record_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_run_record_detail_in")]
  public partial class req_run_record_detail_in : global::ProtoBuf.IExtensible
  {
    public req_run_record_detail_in() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_run_record_detail")]
  public partial class req_run_record_detail : global::ProtoBuf.IExtensible
  {
    public req_run_record_detail() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private com.sporger.server.proto.model.run_report_in _run_record_detail;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"run_record_detail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.run_report_in run_record_detail
    {
      get { return _run_record_detail; }
      set { _run_record_detail = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"run_best_record")]
  public partial class run_best_record : global::ProtoBuf.IExtensible
  {
    public run_best_record() {}
    
    private uint _runType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"runType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint runType
    {
      get { return _runType; }
      set { _runType = value; }
    }
    private uint _runDistance;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"runDistance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint runDistance
    {
      get { return _runDistance; }
      set { _runDistance = value; }
    }
    private uint _time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _speed;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private uint _useTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"useTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint useTime
    {
      get { return _useTime; }
      set { _useTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_run_best_record_list_out")]
  public partial class req_run_best_record_list_out : global::ProtoBuf.IExtensible
  {
    public req_run_best_record_list_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.run_best_record> _run_best_record_list = new global::System.Collections.Generic.List<com.sporger.server.proto.model.run_best_record>();
    [global::ProtoBuf.ProtoMember(1, Name=@"run_best_record_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.run_best_record> run_best_record_list
    {
      get { return _run_best_record_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_free_run_end_in")]
  public partial class req_free_run_end_in : global::ProtoBuf.IExtensible
  {
    public req_free_run_end_in() {}
    
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_run_report_out")]
  public partial class notify_run_report_out : global::ProtoBuf.IExtensible
  {
    public notify_run_report_out() {}
    
    private com.sporger.server.proto.model.run_report_in _runReport;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"runReport", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.run_report_in runReport
    {
      get { return _runReport; }
      set { _runReport = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_level_star_end_out")]
  public partial class notify_level_star_end_out : global::ProtoBuf.IExtensible
  {
    public notify_level_star_end_out() {}
    
    private com.sporger.server.proto.model.level_star_info _levelStarInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"levelStarInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.level_star_info levelStarInfo
    {
      get { return _levelStarInfo; }
      set { _levelStarInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_gm_levelup_out")]
  public partial class notify_gm_levelup_out : global::ProtoBuf.IExtensible
  {
    public notify_gm_levelup_out() {}
    
    private uint _levelId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"levelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint levelId
    {
      get { return _levelId; }
      set { _levelId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_warm_body_finish_in")]
  public partial class req_warm_body_finish_in : global::ProtoBuf.IExtensible
  {
    public req_warm_body_finish_in() {}
    
    private uint _MapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MapId
    {
      get { return _MapId; }
      set { _MapId = value; }
    }
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}