//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoFriend.proto
// Note: requires additional types generated from: model/ProtoBag.proto
// Note: requires additional types generated from: model/ProtoPlayer.proto
// Note: requires additional types generated from: model/ProtoLocation.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"friend_relation_info")]
  public partial class friend_relation_info : global::ProtoBuf.IExtensible
  {
    public friend_relation_info() {}
    
    private string _palyerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"palyerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string palyerId
    {
      get { return _palyerId; }
      set { _palyerId = value; }
    }
    private uint _attentionState;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"attentionState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint attentionState
    {
      get { return _attentionState; }
      set { _attentionState = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"player_base_info")]
  public partial class player_base_info : global::ProtoBuf.IExtensible
  {
    public player_base_info() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _headIconId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"headIconId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string headIconId
    {
      get { return _headIconId; }
      set { _headIconId = value; }
    }
    private string _playerName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _sex;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"player_now_state_info")]
  public partial class player_now_state_info : global::ProtoBuf.IExtensible
  {
    public player_now_state_info() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _playerState;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerState
    {
      get { return _playerState; }
      set { _playerState = value; }
    }
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private uint _howLong;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"howLong", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint howLong
    {
      get { return _howLong; }
      set { _howLong = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_friends_relation_in")]
  public partial class req_friends_relation_in : global::ProtoBuf.IExtensible
  {
    public req_friends_relation_in() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_friends_relation_out")]
  public partial class req_friends_relation_out : global::ProtoBuf.IExtensible
  {
    public req_friends_relation_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.friend_relation_info> _friendsRelation = new global::System.Collections.Generic.List<com.sporger.server.proto.model.friend_relation_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"friendsRelation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.friend_relation_info> friendsRelation
    {
      get { return _friendsRelation; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_player_friends_in")]
  public partial class req_player_friends_in : global::ProtoBuf.IExtensible
  {
    public req_player_friends_in() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _pageIndex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pageIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pageIndex
    {
      get { return _pageIndex; }
      set { _pageIndex = value; }
    }
    private uint _pagesNumber;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pagesNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pagesNumber
    {
      get { return _pagesNumber; }
      set { _pagesNumber = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_player_friends_out")]
  public partial class req_player_friends_out : global::ProtoBuf.IExtensible
  {
    public req_player_friends_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.player_base_info> _players = new global::System.Collections.Generic.List<com.sporger.server.proto.model.player_base_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.player_base_info> players
    {
      get { return _players; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_search_player_in")]
  public partial class req_search_player_in : global::ProtoBuf.IExtensible
  {
    public req_search_player_in() {}
    
    private string _playerName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_search_player_out")]
  public partial class req_search_player_out : global::ProtoBuf.IExtensible
  {
    public req_search_player_out() {}
    
    private com.sporger.server.proto.model.player_base_info _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.player_base_info player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_attention_player_in")]
  public partial class req_attention_player_in : global::ProtoBuf.IExtensible
  {
    public req_attention_player_in() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private bool _isAttention;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isAttention", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isAttention
    {
      get { return _isAttention; }
      set { _isAttention = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_player_attention")]
  public partial class notify_player_attention : global::ProtoBuf.IExtensible
  {
    public notify_player_attention() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_player_base_info_in")]
  public partial class req_player_base_info_in : global::ProtoBuf.IExtensible
  {
    public req_player_base_info_in() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_player_base_info_out")]
  public partial class req_player_base_info_out : global::ProtoBuf.IExtensible
  {
    public req_player_base_info_out() {}
    
    private com.sporger.server.proto.model.player_base_info _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.player_base_info player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_friend_state_in")]
  public partial class req_friend_state_in : global::ProtoBuf.IExtensible
  {
    public req_friend_state_in() {}
    
    private readonly global::System.Collections.Generic.List<string> _playerIds = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playerIds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> playerIds
    {
      get { return _playerIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_friend_state_out")]
  public partial class req_friend_state_out : global::ProtoBuf.IExtensible
  {
    public req_friend_state_out() {}
    
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.player_now_state_info> _state = new global::System.Collections.Generic.List<com.sporger.server.proto.model.player_now_state_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.player_now_state_info> state
    {
      get { return _state; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_join_game_in")]
  public partial class req_join_game_in : global::ProtoBuf.IExtensible
  {
    public req_join_game_in() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_join_game_out")]
  public partial class req_join_game_out : global::ProtoBuf.IExtensible
  {
    public req_join_game_out() {}
    
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_visit_game_in")]
  public partial class req_visit_game_in : global::ProtoBuf.IExtensible
  {
    public req_visit_game_in() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_visit_game_out")]
  public partial class req_visit_game_out : global::ProtoBuf.IExtensible
  {
    public req_visit_game_out() {}
    
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private ulong _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.player_simple_info> _players = new global::System.Collections.Generic.List<com.sporger.server.proto.model.player_simple_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.player_simple_info> players
    {
      get { return _players; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.location_in> _player_init_location = new global::System.Collections.Generic.List<com.sporger.server.proto.model.location_in>();
    [global::ProtoBuf.ProtoMember(4, Name=@"player_init_location", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.location_in> player_init_location
    {
      get { return _player_init_location; }
    }
  
    private ulong _raceStartTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"raceStartTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong raceStartTime
    {
      get { return _raceStartTime; }
      set { _raceStartTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_player_detailed_in")]
  public partial class req_player_detailed_in : global::ProtoBuf.IExtensible
  {
    public req_player_detailed_in() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_player_detailed_out")]
  public partial class req_player_detailed_out : global::ProtoBuf.IExtensible
  {
    public req_player_detailed_out() {}
    
    private com.sporger.server.proto.model.player_base_info _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.sporger.server.proto.model.player_base_info player
    {
      get { return _player; }
      set { _player = value; }
    }
    private string _familyName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"familyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string familyName
    {
      get { return _familyName; }
      set { _familyName = value; }
    }
    private string _runGroupName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"runGroupName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string runGroupName
    {
      get { return _runGroupName; }
      set { _runGroupName = value; }
    }
    private uint _sporgerTotal;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sporgerTotal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sporgerTotal
    {
      get { return _sporgerTotal; }
      set { _sporgerTotal = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.game_item_detail_info> _equip_info = new global::System.Collections.Generic.List<com.sporger.server.proto.model.game_item_detail_info>();
    [global::ProtoBuf.ProtoMember(5, Name=@"equip_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.game_item_detail_info> equip_info
    {
      get { return _equip_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_friend_message_in")]
  public partial class req_friend_message_in : global::ProtoBuf.IExtensible
  {
    public req_friend_message_in() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_friend_message_out")]
  public partial class req_friend_message_out : global::ProtoBuf.IExtensible
  {
    public req_friend_message_out() {}
    
    private string _message = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_delect_friend_message_in")]
  public partial class req_delect_friend_message_in : global::ProtoBuf.IExtensible
  {
    public req_delect_friend_message_in() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}