//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoMap.proto
namespace com.sporger.server.proto.model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_enter_map_in")]
  public partial class req_enter_map_in : global::ProtoBuf.IExtensible
  {
    public req_enter_map_in() {}
    
    private uint _MapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MapId
    {
      get { return _MapId; }
      set { _MapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_enter_map_out")]
  public partial class req_enter_map_out : global::ProtoBuf.IExtensible
  {
    public req_enter_map_out() {}
    
    private uint _MapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MapId
    {
      get { return _MapId; }
      set { _MapId = value; }
    }
    private ulong _roomId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private string _channelId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"enter_map_in")]
  public partial class enter_map_in : global::ProtoBuf.IExtensible
  {
    public enter_map_in() {}
    
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private ulong _roomId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"enter_map_out")]
  public partial class enter_map_out : global::ProtoBuf.IExtensible
  {
    public enter_map_out() {}
    
    private uint _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"notify_activity_end_out")]
  public partial class notify_activity_end_out : global::ProtoBuf.IExtensible
  {
    public notify_activity_end_out() {}
    
    private uint _remainTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"remainTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint remainTime
    {
      get { return _remainTime; }
      set { _remainTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"npc_player_info")]
  public partial class npc_player_info : global::ProtoBuf.IExtensible
  {
    public npc_player_info() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _speed = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> speed
    {
      get { return _speed; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"rank_player_info")]
  public partial class rank_player_info : global::ProtoBuf.IExtensible
  {
    public rank_player_info() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _userName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string time
    {
      get { return _time; }
      set { _time = value; }
    }
    private string _userId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_enter_career_map_in")]
  public partial class req_enter_career_map_in : global::ProtoBuf.IExtensible
  {
    public req_enter_career_map_in() {}
    
    private uint _MapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MapId
    {
      get { return _MapId; }
      set { _MapId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_enter_career_map_out")]
  public partial class req_enter_career_map_out : global::ProtoBuf.IExtensible
  {
    public req_enter_career_map_out() {}
    
    private uint _MapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MapId
    {
      get { return _MapId; }
      set { _MapId = value; }
    }
    private ulong _roomId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.npc_player_info> _npcPlayerInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.npc_player_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"npcPlayerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.npc_player_info> npcPlayerInfo
    {
      get { return _npcPlayerInfo; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sporger.server.proto.model.rank_player_info> _rankPlayerInfo = new global::System.Collections.Generic.List<com.sporger.server.proto.model.rank_player_info>();
    [global::ProtoBuf.ProtoMember(4, Name=@"rankPlayerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sporger.server.proto.model.rank_player_info> rankPlayerInfo
    {
      get { return _rankPlayerInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}