//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model/ProtoCommon.proto
namespace com.sporger.server.proto.model
{
    [global::ProtoBuf.ProtoContract(Name=@"MessageType")]
    public enum MessageType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_VALIDATE", Value=1)]
      LOGIN_VALIDATE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_VALIDATE_RECONNECT", Value=2)]
      LOGIN_VALIDATE_RECONNECT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_BE_KICKED_OFF", Value=3)]
      NOTIFY_BE_KICKED_OFF = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHARACTER_ATTRIBUTE", Value=100)]
      CHARACTER_ATTRIBUTE = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_WEAR_EQUIP", Value=101)]
      REQ_WEAR_EQUIP = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_UNINSTALL_EQUIP", Value=102)]
      REQ_UNINSTALL_EQUIP = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CHARACTER_CURRENCY", Value=103)]
      NOTIFY_CHARACTER_CURRENCY = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CHARACTER_LEVEL_UP", Value=104)]
      NOTIFY_CHARACTER_LEVEL_UP = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_EQUIP_ATTRS", Value=150)]
      REQ_EQUIP_ATTRS = 150,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SELL_ITME", Value=151)]
      REQ_SELL_ITME = 151,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_USE_ITEM", Value=152)]
      REQ_USE_ITEM = 152,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_EQUIP_START_UP", Value=153)]
      REQ_EQUIP_START_UP = 153,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_DRAW_REWARD", Value=154)]
      REQ_DRAW_REWARD = 154,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_DAILY_MISSION_LIST", Value=200)]
      REQ_DAILY_MISSION_LIST = 200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_DAILY_MISSION_REWARD", Value=201)]
      REQ_DAILY_MISSION_REWARD = 201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_TUTORIAL_INFO", Value=225)]
      REQ_TUTORIAL_INFO = 225,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SAVE_TUTORIAL", Value=226)]
      REQ_SAVE_TUTORIAL = 226,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SAVE_TRIGGER_TUTORIAL", Value=227)]
      REQ_SAVE_TRIGGER_TUTORIAL = 227,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SAVE_CAREER_PLOT", Value=228)]
      REQ_SAVE_CAREER_PLOT = 228,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PLAYER_FRIENDS", Value=350)]
      REQ_PLAYER_FRIENDS = 350,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_FRIEND_STATE", Value=351)]
      REQ_FRIEND_STATE = 351,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_FRIEND_DETAILED", Value=352)]
      REQ_FRIEND_DETAILED = 352,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ATTENTION_PLAYER", Value=353)]
      REQ_ATTENTION_PLAYER = 353,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_PLAYER_ATTENTION", Value=354)]
      NOTIFY_PLAYER_ATTENTION = 354,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_JOIN_GAME", Value=355)]
      REQ_JOIN_GAME = 355,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_VISIT_GAME", Value=356)]
      REQ_VISIT_GAME = 356,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_FRIEND_MESSAGE", Value=357)]
      REQ_FRIEND_MESSAGE = 357,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_DELECT_FRIEND_MESSAGE", Value=358)]
      REQ_DELECT_FRIEND_MESSAGE = 358,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_FRIENDS_RELATION", Value=359)]
      REQ_FRIENDS_RELATION = 359,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SEARCH_PLAYER", Value=360)]
      REQ_SEARCH_PLAYER = 360,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PLAYER_BASE_INFO", Value=361)]
      REQ_PLAYER_BASE_INFO = 361,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_MAP", Value=400)]
      REQ_ENTER_MAP = 400,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTER_MAP", Value=401)]
      ENTER_MAP = 401,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_GOIN_INSTANCE", Value=402)]
      PLAYER_GOIN_INSTANCE = 402,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_EXIT_INSTANCE", Value=403)]
      PLAYER_EXIT_INSTANCE = 403,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYNC_PLAYER_INSTANCE_POS", Value=404)]
      SYNC_PLAYER_INSTANCE_POS = 404,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SERVER_TIME", Value=405)]
      REQ_SERVER_TIME = 405,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HEARTBEAT", Value=406)]
      HEARTBEAT = 406,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MATCHING", Value=407)]
      REQ_MATCHING = 407,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CANCEL_MATCHING", Value=408)]
      REQ_CANCEL_MATCHING = 408,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MATCHING_RESULT", Value=409)]
      NOTIFY_MATCHING_RESULT = 409,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_PRE_SCENE", Value=410)]
      REQ_ENTER_PRE_SCENE = 410,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_PLAYER_READY_ENTER_PRE_SCENE", Value=411)]
      NOTIFY_PLAYER_READY_ENTER_PRE_SCENE = 411,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_PERMITE_ENTER_PRE_SCENE", Value=412)]
      NOTIFY_PERMITE_ENTER_PRE_SCENE = 412,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SELECT_SCENE", Value=413)]
      REQ_SELECT_SCENE = 413,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CHANGE_SCENE", Value=414)]
      NOTIFY_CHANGE_SCENE = 414,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_READY", Value=415)]
      REQ_READY = 415,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_READY", Value=416)]
      NOTIFY_READY = 416,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CHANGE_ROOM_OWNER", Value=417)]
      NOTIFY_CHANGE_ROOM_OWNER = 417,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_START_RACE", Value=420)]
      NOTIFY_START_RACE = 420,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CAREER_RUN_END", Value=421)]
      NOTIFY_CAREER_RUN_END = 421,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_FREE_RUN_END", Value=422)]
      REQ_FREE_RUN_END = 422,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_PLAYER_REACH", Value=423)]
      NOTIFY_PLAYER_REACH = 423,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_OUTDOOR_PVP_RESULT", Value=424)]
      NOTIFY_OUTDOOR_PVP_RESULT = 424,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_ITEM_PVP_RESULT", Value=425)]
      NOTIFY_ITEM_PVP_RESULT = 425,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PLAYER_LIST", Value=426)]
      REQ_PLAYER_LIST = 426,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_NEW_PLAYER_LIST_SIMPLE_INFO", Value=427)]
      REQ_NEW_PLAYER_LIST_SIMPLE_INFO = 427,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CONFIRM_MATCHING_TIME_OUT", Value=428)]
      NOTIFY_CONFIRM_MATCHING_TIME_OUT = 428,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_LEVEL_STAR_END", Value=429)]
      NOTIFY_LEVEL_STAR_END = 429,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_CAREER_MAP", Value=430)]
      REQ_ENTER_CAREER_MAP = 430,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_REALTIME_VOICE", Value=450)]
      REQ_REALTIME_VOICE = 450,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CANCEL_REALTIME_VOICE", Value=451)]
      REQ_CANCEL_REALTIME_VOICE = 451,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ACCEPT_REALTIME_VOICE", Value=452)]
      REQ_ACCEPT_REALTIME_VOICE = 452,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_HANGUP_REALTIME_VOICE", Value=453)]
      REQ_HANGUP_REALTIME_VOICE = 453,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_REALTIME_VOICE_REQ", Value=454)]
      NOTIFY_REALTIME_VOICE_REQ = 454,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_REALTIME_VOICE_REQ_FAILURE", Value=455)]
      NOTIFY_REALTIME_VOICE_REQ_FAILURE = 455,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_PLAYER_JOIN_REALTIME_VOICE_ROOM", Value=456)]
      NOTIFY_PLAYER_JOIN_REALTIME_VOICE_ROOM = 456,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CANCEL_REALTIME_VOICE_REQ", Value=457)]
      NOTIFY_CANCEL_REALTIME_VOICE_REQ = 457,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_PLAYER_LEAVE_REALTIME_VOICE_ROOM", Value=458)]
      NOTIFY_PLAYER_LEAVE_REALTIME_VOICE_ROOM = 458,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_FAM", Value=501)]
      REQ_ENTER_FAM = 501,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_FAM_MAP", Value=502)]
      REQ_ENTER_FAM_MAP = 502,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_OPEN_TREASURE_BOX", Value=503)]
      REQ_OPEN_TREASURE_BOX = 503,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_BOX_AND_ITEM_LIST", Value=505)]
      NOTIFY_BOX_AND_ITEM_LIST = 505,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_OPEN_TREASURE_BOX", Value=506)]
      NOTIFY_OPEN_TREASURE_BOX = 506,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PICK_OPEN_TREASURE_BOX_ITEM", Value=507)]
      REQ_PICK_OPEN_TREASURE_BOX_ITEM = 507,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_PICK_OPEN_TREASURE_ITEM", Value=508)]
      NOTIFY_PICK_OPEN_TREASURE_ITEM = 508,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_DISCARD_OPEN_TREASURE_BOX_ITEM", Value=509)]
      REQ_DISCARD_OPEN_TREASURE_BOX_ITEM = 509,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_SPAWN_ORDINARY_BOX", Value=510)]
      NOTIFY_SPAWN_ORDINARY_BOX = 510,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_SPAWN_ITEM_AND_BOX", Value=511)]
      NOTIFY_SPAWN_ITEM_AND_BOX = 511,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_SPAWN_MP_ORDINARY_BOX", Value=512)]
      NOTIFY_SPAWN_MP_ORDINARY_BOX = 512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_OPEN_MP_ORDINARY_BOX_STAND_POS", Value=513)]
      NOTIFY_OPEN_MP_ORDINARY_BOX_STAND_POS = 513,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_RESTORE_MP_ORDINARY_BOX_STAND_POS", Value=514)]
      NOTIFY_RESTORE_MP_ORDINARY_BOX_STAND_POS = 514,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_ACTIVITY_END", Value=518)]
      NOTIFY_ACTIVITY_END = 518,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MAZE_MATCHING", Value=551)]
      REQ_MAZE_MATCHING = 551,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_MATCHING_RESULT", Value=552)]
      NOTIFY_MAZE_MATCHING_RESULT = 552,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MAZE_CANCEL_MATCHING", Value=553)]
      REQ_MAZE_CANCEL_MATCHING = 553,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_WAIT_COUNT_DOWN", Value=554)]
      NOTIFY_MAZE_WAIT_COUNT_DOWN = 554,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_START_GAME_COUNT_DOWN", Value=555)]
      NOTIFY_MAZE_START_GAME_COUNT_DOWN = 555,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_START_GAME", Value=556)]
      NOTIFY_MAZE_START_GAME = 556,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_PLAYER_NOT_ENOUGH", Value=557)]
      NOTIFY_MAZE_PLAYER_NOT_ENOUGH = 557,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MAZE_DESTROY_DOOR", Value=558)]
      REQ_MAZE_DESTROY_DOOR = 558,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_DESTROY_DOOR", Value=559)]
      NOTIFY_MAZE_DESTROY_DOOR = 559,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_SPAWN_DOOR", Value=560)]
      NOTIFY_MAZE_SPAWN_DOOR = 560,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_FINISH_POINT", Value=562)]
      REQ_ENTER_FINISH_POINT = 562,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_FINISH_MAZE_GAME", Value=563)]
      NOTIFY_FINISH_MAZE_GAME = 563,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_CHARACTER_ENERGE", Value=564)]
      NOTIFY_MAZE_CHARACTER_ENERGE = 564,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MAZE_PICK_ENERGE_ITEM", Value=565)]
      REQ_MAZE_PICK_ENERGE_ITEM = 565,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_SPAWN_ENERGE_ITEM", Value=566)]
      NOTIFY_MAZE_SPAWN_ENERGE_ITEM = 566,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_MAZE_PICK_ENERGE_ITEM", Value=567)]
      NOTIFY_MAZE_PICK_ENERGE_ITEM = 567,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_WATCH_RACE_FINISHED", Value=601)]
      NOTIFY_WATCH_RACE_FINISHED = 601,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_SQUARE", Value=701)]
      REQ_ENTER_SQUARE = 701,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_HOT_SQUARE_CHAT_GROUP", Value=702)]
      REQ_HOT_SQUARE_CHAT_GROUP = 702,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CREATE_SQUARE_CHAT_GROUP", Value=703)]
      REQ_CREATE_SQUARE_CHAT_GROUP = 703,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_ADVERTISEMENT", Value=704)]
      NOTIFY_ADVERTISEMENT = 704,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_SQUARE_CHAT_GROUP", Value=705)]
      REQ_ENTER_SQUARE_CHAT_GROUP = 705,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_ENTER_SQUARE_CHAT_GROUP", Value=706)]
      NOTIFY_ENTER_SQUARE_CHAT_GROUP = 706,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SQUARE_CHAT_INFO", Value=707)]
      REQ_SQUARE_CHAT_INFO = 707,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_SQUARE_CHAT_INFO", Value=708)]
      NOTIFY_SQUARE_CHAT_INFO = 708,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CLOSE_SQUARE_CHAT_GROUP", Value=709)]
      REQ_CLOSE_SQUARE_CHAT_GROUP = 709,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_EXIT_SQUARE_CHAT_GROUP", Value=710)]
      REQ_EXIT_SQUARE_CHAT_GROUP = 710,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CLOSE_CHAT_GROUP", Value=711)]
      NOTIFY_CLOSE_CHAT_GROUP = 711,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_EXIT_CHAT_GROUP", Value=712)]
      NOTIFY_EXIT_CHAT_GROUP = 712,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SQUARE_INVITE_FRIEND", Value=713)]
      REQ_SQUARE_INVITE_FRIEND = 713,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SQUARE_INVITE_AGREE_FRIEND", Value=714)]
      REQ_SQUARE_INVITE_AGREE_FRIEND = 714,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RAINBOWRUN_MATCHING", Value=801)]
      REQ_RAINBOWRUN_MATCHING = 801,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_RAINBOWRUN_MATCHING_RESULT", Value=802)]
      NOTIFY_RAINBOWRUN_MATCHING_RESULT = 802,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RAINBOWRUN_CANCEL_MATCHING", Value=803)]
      REQ_RAINBOWRUN_CANCEL_MATCHING = 803,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RAINBOWRUN_CHANGE_TRACK", Value=804)]
      REQ_RAINBOWRUN_CHANGE_TRACK = 804,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_RAINBOWRUN_CHANGE_TRACK", Value=805)]
      NOTIFY_RAINBOWRUN_CHANGE_TRACK = 805,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_RAINBOWRUN_CURRENT_INFO", Value=806)]
      NOTIFY_RAINBOWRUN_CURRENT_INFO = 806,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_RAINBOWRUN_GAMEOVER", Value=807)]
      NOTIFY_RAINBOWRUN_GAMEOVER = 807,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RAINBOWRUN_READY", Value=808)]
      REQ_RAINBOWRUN_READY = 808,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_RAINBOWRUN_READY", Value=809)]
      NOTIFY_RAINBOWRUN_READY = 809,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_RAINBOWRUN_LOAD_SCENE", Value=810)]
      NOTIFY_RAINBOWRUN_LOAD_SCENE = 810,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOCATION", Value=999)]
      LOCATION = 999,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CHARACTER_STATUS", Value=1000)]
      REQ_CHARACTER_STATUS = 1000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_CHARACTER_STATUS", Value=1001)]
      NOTIFY_CHARACTER_STATUS = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MAZE_CHARACTER_STATUS", Value=1002)]
      REQ_MAZE_CHARACTER_STATUS = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CITY_CHARACTER_STATUS", Value=1003)]
      REQ_CITY_CHARACTER_STATUS = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RAINBOW_RUN_CHARACTER_STATUS", Value=1004)]
      REQ_RAINBOW_RUN_CHARACTER_STATUS = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RUN_REPORT", Value=3000)]
      RUN_REPORT = 3000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RUN_BASE_INFO", Value=3001)]
      REQ_RUN_BASE_INFO = 3001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PULL_RUN_RECORD", Value=3002)]
      REQ_PULL_RUN_RECORD = 3002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RUN_BEST_RECORD_LIST", Value=3003)]
      REQ_RUN_BEST_RECORD_LIST = 3003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RUN_RECORD_DETAIL", Value=3004)]
      REQ_RUN_RECORD_DETAIL = 3004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_SPORGER_CHANGE", Value=3005)]
      NOTIFY_SPORGER_CHANGE = 3005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_WARM_BODY_FINISH", Value=3006)]
      REQ_WARM_BODY_FINISH = 3006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_RUN_REPORT", Value=3007)]
      NOTIFY_RUN_REPORT = 3007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_GET_REWARD", Value=5000)]
      NOTIFY_GET_REWARD = 5000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_GM_LEVELUP", Value=5001)]
      NOTIFY_GM_LEVELUP = 5001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_GM_COMMAND", Value=10000)]
      REQ_GM_COMMAND = 10000
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PlayerState")]
    public enum PlayerState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OFFLINE", Value=0)]
      OFFLINE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEISURE", Value=1)]
      LEISURE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SPORTS", Value=2)]
      SPORTS = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"AttentionState")]
    public enum AttentionState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONCERNED", Value=0)]
      CONCERNED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BECONCERNED", Value=1)]
      BECONCERNED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MUTUALCONCERNED", Value=2)]
      MUTUALCONCERNED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STRANGER", Value=3)]
      STRANGER = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CharacterState")]
    public enum CharacterState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WALKING", Value=0)]
      WALKING = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIGGING", Value=1)]
      DIGGING = 1
    }
  
}